language: node_js

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
    - node_js: "node"
      before_script:
        - npm run build
        - npm run link
        - danger
    - node_js: "6"
    - node_js: "7"

script:
  - npm run lint
  - npm test -- --coverage --no-cache && rm ./coverage/coverage-final.json

after_success:
  - bash <(curl -s https://codecov.io/bash)